### ISSUE TITLE
Countdown timer in some strange units ?

### ISSUE THREAD

**Issue by cooldemo** [poelzi/OpenChronos#11]
The countdown timer is in some strange units or timer is setup wrong ?

**Comment by cooldemo** [comment]
Ok, found the problem. When stopwatch is also configured, the stopwatch routine also updates the compare register of the timer. The: 
if(!(sStopwatch.state & STOPWATCH_RUN)) return;
should be added to update_stopwatch_timer and also to stopwatch_tick

**Comment by poelzi** [comment]
thanks for the fix. pushed to repo
