### ISSUE TITLE
Problem mit make und python

### ISSUE THREAD

**Issue by Kerm** [poelzi/OpenChronos#2]
Hallo!

Ich weiß, es ist nicht direkt ein PRoblem mit deinem Code, aber da du ja Win7 nutzt solltest du über das selbe Problem gestolpert sein :)

Also ich bekomme bei " make config" immer die Meldung: 
  File "C:\Python31\lib\curses__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
make: **\* [config] Error 1

Hat vielleicht jemand eine Lösung?

Gruß

**Comment by poelzi** [comment]
i don't own any windows, sorry.
maybe some other windows python distribution has curses compiled in. activepython or cygwin python maybe.
otherwise a text gui could be implemented, too

**Comment by ghost** [comment]
Windows simply doesn't provide curses. It might be theoretically possible to get the thing working some way, but basically it won't. 

I very much question the sensibility of making an elaborate specific complex frontend depending on a whole separate dynamic language, bindings, and runtime libraries for generating one simple header file that, especially with good comments, would be easiest to change by hand in the first place.

**Comment by Kerm** [comment]
Hmmm... ok after a couple of hours an google i couldnt find any solution.
I will try it on my Ubuntumachine when i got the time.
Thanks for ur reply.

**Comment by poelzi** [comment]
fixed i hope :-)
