### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by doragasu** [poelzi/OpenChronos#4]
Hi. I'm having problems to build OpenChronos. When I try "make config", I get this error:

---

doragasu@doragasu-C2D:~/src/ez430Chronos/OpenChronos$ make config
python tools/config.py
Traceback (most recent call last):
  File "tools/config.py", line 368, in <module>
    App.run()
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/apNPSApplication.py", line 25, in run
    return npyssafewrapper.wrapper(self.**remove_argument_call_main)
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/npyssafewrapper.py", line 96, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/apNPSApplication.py", line 20, in __remove_argument_call_main
    return self.main()
  File "tools/config.py", line 278, in main
    f = F.add(npyscreen.Checkbox, name=field["name"], value=field["value"])
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/fmForm.py", line 290, in add_widget
    _args, *_keywords)
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/wgcheckbox.py", line 42, in __init**
    super(Checkbox, self).**init**(screen, *_keywords)
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/wgwidget.py", line 178, in **init**
    self.set_size()
  File "/home/doragasu/src/ez430Chronos/OpenChronos/tools/npyscreen/wgwidget.py", line 254, in set_size
    raise Exception("Not enough space: max y and x = %s , %s. Height and Width = %s , %s " % (my, mx, self.height, self.width) ) # unsafe. Need to add error here.
Exception: Not enough space: max y and x = 0 , 77. Height and Width = RAISEERROR , 77 
make: *_\* [config] Error 1

---

I'm trying to build with Ubuntu 10.04 64 bit, GNU make 3.81, msp430-gcc 4.4.3 and python 2.6.5.

Too bad I know nothing about python scripts :(.

**Comment by dkm** [comment]
Try to maximize the terminal in which you run the script ;)

**Comment by doragasu** [comment]
That did the trick, now it configures OK. Thanks a lot!

Now I'm facing compiler errors, I'll try to solve them myself...

**Comment by doragasu** [comment]
OK, I'm stuck compiling. It looks like I'm missing "cc430x613x.h" file. It's not located neither in msp430gcc nor in OpenChronos... Where can I get this file? Is it maybe only included with IAR compiler?

**Comment by dkm** [comment]
How did you get mspgcc ?

**Comment by doragasu** [comment]
I downloaded the recommended one from http://mspgcc4.sourceforge.net/.

First, I downloaded it from the SVN and compiled gcc 4.4.3 myself. Then tried compiling version 4.4.2, without luck. Finally I also tried downloading a pre-built toolchain from http://sourceforge.net/projects/mspgcc4/files/, but "cc430x613x.h" file is also missing in the pre-built package...

**Comment by dkm** [comment]
Ok... I'm using 4.4.3 from svn (rev 139) and everything is fine. I tried the version precompiled on their website, but IIRC, it does not include support for the cc430.
I do have your file in my mspgcc install : msp430/include/cc430x613x.h
I think there is something wrong with your setup.

**Comment by doragasu** [comment]
I'm also in revision 139... this is weird. I'm missing include files for cc430\* devices, but I my installation has the linker scripts for these devices. This is the directory layout of my installation of msp430-gcc:

http://pastebin.com/2G71kjPY

**Comment by dkm** [comment]
Sorry, I don't have any clue...

**Comment by doragasu** [comment]
SOLVED.

When I ran the script to configure and build MSPGCC4, I was selecting the wrong version of msp430-libc. Tried with version 20100430, and now OpenChronos compiles without problems :).

**Comment by poelzi** [comment]
i rewrote the config part. the initial problem should not occure anymore.
