### ISSUE TITLE
Loct message brokenness

### ISSUE THREAD

**Issue by ghost** [poelzi/OpenChronos#5]
I think a recent patch made "loct" (keylock message) turn into "lo?t".

I believe SHA: 37c10e28b9bd6c22a4d80a92ffb8bf986405fba1 changes a c to ? in display1.c although that's probably a c the message shouldn't be using anyway. I haven't looked deep enough to see where the message is generated and if that's done correctly.

**Comment by ghost** [comment]
line 84

**Comment by midluk** [comment]
I have fixed that in master of my fork. Try that.
git://github.com/midluk/OpenChronos.git

**Comment by poelzi** [comment]
thanks midluk. fixed
