### ISSUE TITLE
rfBSL broken

### ISSUE THREAD

**Issue by ghost** [poelzi/OpenChronos#6]
I pulled from origin yesterday and I can't start rfBSL on the watch anymore. I think some time in the past few weeks perhaps some change was introduced that causes this.

Symptoms/procedure:
Start TI control center, choose wireless update, start AP, select fw and start update. When told to start rfbsl on the watch, select rfbsl and press "down". BSL should start. Instead the watch shows "loct". Pressing (not holding) down again displays "open". The messages repeat. rfBSL may well still work, but something makes the button toggle lock instead. ACC and PPT modes work as before.

Changed in config.h: I defined FIXEDPOINT.

**Comment by midluk** [comment]
The currently needed procedure is
1. cycle through menu with "num" until rfbsl is selected
2. press "down" -> open is shown
3. long press "num" -> the update should start

Did you do that?

**Comment by ghost** [comment]
This appears to have been an odd build mishap of some kind on my part. Now it's starting as per readme.
